import './globals.css';
import { Inter } from 'next/font/google';
import BgColor from '@/components/BgColor';
import Header from '@/components/header';
import Footer from '@/components/footer';
import ActiveSectionContextProvider from '@/context/active-section-context';
import { Toaster } from "react-hot-toast";
import ThemeSwitch from '@/components/theme-switch';
import ThemeContextProvider from '@/context/theme-context';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'TJJ |  web rookie',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='!scroll-smooth'>
      <body className={`${inter.className} bg-gray-50 text-gray-950 relative pt-28 sm:pt-36 dark:bg-gray-900 dark:text-gray-50 dark:text-opacity-90`}>
        <ThemeContextProvider>
          <BgColor />
          <ActiveSectionContextProvider>
            <Header />
            <Toaster position="top-right" />
            {children}
            <Footer />
            <ThemeSwitch />
          </ActiveSectionContextProvider>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
